
  SCENE7:{ type:"sequence", steps:[
    { speaker:null, speakerClass:"char-narrator",
      text:"SALA DE CRISIS — REUNION DE EMERGENCIA GLOBAL\n\nHologramas. Mapa del mundo. Puntos rojos multiplicandose.\nQuince rostros en pantalla. Ministerios de salud. Militares. Dos premios Nobel." },
    { speaker:"DIRECTOR — Comite Global de Biodefensa", speakerClass:"char-director",
      text:"Necesitamos clasificacion taxonomica antes de cualquier intervencion.\nSin saber con que dominio tratamos, cualquier tratamiento podria acelerar la adaptacion.",
      alert:{ type:"danger", msg:"⚠ COMITÉ GLOBAL — SESIÓN DE EMERGENCIA — NIVEL MÁXIMO" } },
    { speaker:"MENTORA — Dra. Elena Vargas", speakerClass:"char-mentora",
      text:"(Te mira desde el otro lado de la sala.)\n\nTienes los datos de distancia genomica. El arbol filogenetico. Ubica CG-001." },
    { speaker:"TU", speakerClass:"char-player",
      text:"(mirando la matriz)\n\nDame un momento.",
      choices:[
        { label:"(Analizar la fila completa de CG-001 antes de responder.)", next:"SCENE7B", safe:true },
        { label:"(Senalar Archaea — la distancia 0.74 parece razonable.)", next:"SCENE7B", safe:false,
          penalty:{ reason:"Tomaste una decision sin analizar la fila completa de CG-001.",
            lesson:"En analisis filogenetico, siempre compara TODOS los valores antes de concluir. 0.74 parece cercano hasta que ves que Bacteria es 0.18. El contexto comparativo lo es todo: nunca uses un dato aislado para clasificar." } },
        { label:"(Confirmar las unidades de la matriz antes de interpretar.)", next:"SCENE7B", safe:true },
      ] },
  ], next:"SCENE7B" },

  SCENE7B:{ type:"sequence", steps:[
    { speaker:"SISTEMA IA", speakerClass:"char-sistema",
      text:"Matriz de distancias genomicas cargada. Rango 0.00-1.00.\n0 = identico. 1 = sin relacion evolutiva detectable.",
      alert:{ type:"info", msg:"◆ MATRIZ DE DISTANCIAS — ÁRBOL FILOGENÉTICO INTERACTIVO — LISTO" } },
  ], next:"MG3" },

  MG3:{ type:"minigame", game:"phylo", next:"SCENE8" },

  SCENE8:{ type:"sequence", steps:[
    { speaker:"SISTEMA IA", speakerClass:"char-sistema",
      text:"Clasificacion: Dominio Bacteria. Distancia minima 0.18 con Bacteria_Ref.\nAnomalia: fragmentos genicos arqueales funcionales detectados — HGT multidominio.",
      alert:{ type:"danger", msg:"⚠ HGT CONFIRMADA — GENES ARCHAEA FUNCIONALES EN GENOMA BACTERIANO — PROTOCOLO ESPECIAL" } },
    { speaker:"DIRECTOR — Comite Global de Biodefensa", speakerClass:"char-director",
      text:"Transferencia horizontal de genes entre dominios? En esta escala?" },
    { speaker:"TU", speakerClass:"char-player",
      text:"Ocurre naturalmente en entornos extremos. Lo inusual es que los genes transferidos sean funcionales\ny confieran capacidades de multiples dominios simultaneamente.",
      choices:[
        { label:"Los antibioticos bacterianos solo atacaran la mitad de su maquinaria.", next:"SCENE8B", safe:true },
        { label:"Usar antivirales de amplio espectro — son mas seguros en estos casos.", next:"SCENE8B", safe:false,
          penalty:{ reason:"CG-001 es bacteriano. Los antivirales no tienen efecto sobre bacterias ni archaea.",
            lesson:"La clasificacion taxonomica determina el arsenal terapeutico. Antibioticos atacan sintesis proteica o pared bacteriana. Antivirales bloquean replicacion viral. Un organismo bacteriano con genes arqueales requiere estrategia mixta, nunca antiviral como primera linea." } },
        { label:"Necesitamos identificar que genes son arqueales para disenar el blanco.", next:"SCENE8B", safe:true },
      ] },
  ], next:"SCENE8B" },

  SCENE8B:{ type:"sequence", steps:[
    { speaker:"MENTORA — Dra. Elena Vargas", speakerClass:"char-mentora",
      text:"Por eso clasificamos las cuatro mutaciones clave ahora.\nDos son reversibles con CRISPR. Las otras dos...\n\n(pausa)\n\n...necesito que lo confirmes tu.",
      alert:{ type:"warn", msg:"◆ 4 GENES CRÍTICOS — CLASIFICACIÓN REQUERIDA ANTES DE CUALQUIER INTERVENCIÓN" } },
    { speaker:"ANALISTA — Ing. Tomas Reyes", speakerClass:"char-analista",
      text:"120 segundos antes de que el Director exija respuesta al comite.\nClasifica rapido." },
  ], next:"MG4" },

  MG4:{ type:"minigame", game:"mutations", next:"SCENE9" },

  SCENE9:{ type:"sequence", steps:[
    { speaker:"SISTEMA IA", speakerClass:"char-sistema",
      text:"Analisis completado:\n\n  GEN A: SNP missense — REVERSIBLE con CRISPR base editing\n  GEN B: Sin mutacion — NO intervenir\n  GEN C: Insercion in-frame — PARCIALMENTE reversible\n  GEN D: Frameshift -1 — IRREVERSIBLE con tecnologia actual",
      alert:{ type:"danger", msg:"⚠ GEN D FRAMESHIFT PERMANENTE — 68 HORAS PARA PUNTO DE NO RETORNO ECOLÓGICO" } },
    { speaker:"DIRECTOR — Comite Global de Biodefensa", speakerClass:"char-director",
      text:"68 horas. Si no intervenimos antes de ese umbral, los cambios en las cadenas alimentarias seran permanentes.\n\nNecesito una recomendacion ahora." },
    { speaker:"ANALISTA — Ing. Tomas Reyes", speakerClass:"char-analista",
      text:"Tenemos tres opciones tecnicas. Cada una tiene consecuencias que van mas alla de la biologia." },
  ], next:"SCENE10" },

  SCENE10:{ type:"sequence", steps:[
    { speaker:null, speakerClass:"char-narrator",
      text:"La sala queda en silencio.\n\nTodos miran la pantalla donde estan tus analisis.\nEl mapa del mundo sigue actualizandose. Los puntos rojos siguen apareciendo.\n\nEl peso de lo que esta por decidirse es fisico, palpable." },
    { speaker:"MENTORA — Dra. Elena Vargas", speakerClass:"char-mentora",
      text:"(en voz baja, solo para ti)\n\nCualquier decision que tomes tendra consecuencias que no podemos predecir completamente.\nLos datos que analizaste son reales. El frameshift del Gen D es real.\n\nPero tambien es real que esto nunca habia ocurrido antes." },
    { speaker:"TU", speakerClass:"char-player",
      text:"(mirando el genoma completo de CG-001)\n\nHay algo que todavia no hemos analizado.\n\nEste organismo no tiene secuencias de patogenicidad clasicas.\nNo tiene genes de toxinas. No tiene sistemas de evasion inmune activos.\n\nQue quiere, exactamente?" },
    { speaker:"MENTORA — Dra. Elena Vargas", speakerClass:"char-mentora",
      text:"(silencio largo)\n\nEsa es la pregunta correcta.\n\nY es exactamente la que define que hacemos ahora." },
  ], next:"DECISION" },

  DECISION:{ type:"decision",
    text:"Has analizado todo el sistema. Gen D tiene un frameshift irreversible. Los genes A y C son intervenibles. CG-001 no tiene patrones de patogenicidad clasica.\n\n68 horas para el punto de no retorno.\n\nElige.",
    options:[
      { label:"NEUTRALIZAR — Secuencia antisentido CRISPR que silencia los genes A, C y D. Detencion permanente.", next:"END_A",
        sublabel:"Certeza maxima. Costo: perdida permanente de datos geneticos unicos." },
      { label:"CONTENER — Barreras biologicas de ARNi que limitan CG-001 a zonas controladas para estudio.", next:"END_B",
        sublabel:"Equilibrio inestable. Riesgo: mutacion adicional que rompa la contencion." },
      { label:"COMUNICAR — Transmitir el codigo genetico universal como senal de reconocimiento.", next:"END_C",
        sublabel:"Riesgo maximo. Potencial transformador. Irreversible en cualquier direccion." },
    ]
  },

  END_A:{ type:"sequence", steps:[
    { speaker:null, speakerClass:"char-narrator",
      text:"LABORATORIO DE SÍNTESIS — 6 HORAS DESPUÉS\n\nLa secuencia antisentido esta lista. Un vector de entrega disenado para saturar los sitios de union de los genes A, C y D simultaneamente.",
      alert:{ type:"warn", msg:"◆ SECUENCIA ANTISENTIDO LISTA — PROTOCOLO DE ENTREGA EN 30 MINUTOS" } },
    { speaker:"ANALISTA — Ing. Tomas Reyes", speakerClass:"char-analista",
      text:"Una vez que esto se libere, no hay vuelta atras.\nCG-001 queda silenciado permanentemente en todos los entornos afectados." },
    { speaker:"TU", speakerClass:"char-player",
      text:"Lo se.\n\n(pausa)\n\nHazlo." },
    { speaker:null, speakerClass:"char-narrator",
      text:"24 HORAS DESPUÉS\n\nLas curvas epidemiologicas se aplanan. Los casos nuevos caen a cero en 18 horas.\nLos sistemas inmunes de los pacientes existentes comienzan a recuperarse.\n\nCG-001 desaparece de todas las muestras monitoreadas.",
      alert:{ type:"success", msg:"✓ NEUTRALIZACIÓN EXITOSA — CASOS NUEVOS: 0 — RECUPERACIÓN EN PROGRESO" } },
    { speaker:"DIRECTOR — Comite Global de Biodefensa", speakerClass:"char-director",
      text:"Crisis contenida. El mundo puede respirar.\n\n(pausa)\n\nBuen trabajo." },
    { speaker:"MENTORA — Dra. Elena Vargas", speakerClass:"char-mentora",
      text:"(en privado, mas tarde)\n\nHiciste lo correcto.\n\n(pausa larga)\n\nLo hiciste?" },
  ], next:"ENDING_A" },

  ENDING_A:{ type:"ending",
    title:"FINAL A — NEUTRALIZACIÓN",
    subtitle:"EL COSTO DE LA CERTEZA",
    quote:"Elegiste la seguridad.\n\nNo hubo mas muertes. No hubo transicion ecologica.\nEl mundo siguio como antes.\n\nPero en el momento en que la secuencia antisentido saturo los ultimos sitios de union,\nalgo que nunca habiamos visto antes dejo de existir para siempre.\n\nY con ello, respuestas que nunca tendremos.",
    ending_text:"Los epidemiologos publicaron el caso en Nature tres meses despues.\nEl articulo describe CG-001 como la amenaza biologica mas sofisticada jamas documentada.\n\nEn la seccion de discusion, un parrafo:\n\n'La secuencia del Gen D — el unico irreversible — contenia un patron repetido de codones que ningun analisis automatizado pudo clasificar. Su funcion permanece desconocida.'\n\nEn algun servidor de datos genomicos archivados,\nla ultima copia del genoma de CG-001 espera.\nSilenciosa.",
  },

  END_B:{ type:"sequence", steps:[
    { speaker:null, speakerClass:"char-narrator",
      text:"ZONA DE CONTENCIÓN — 12 HORAS DESPUÉS\n\nLas barreras de ARN de interferencia estan desplegadas. Cuatro zonas aisladas en tres continentes.\nLos modelos predictivos dicen que la propagacion esta frenada.",
      alert:{ type:"info", msg:"◆ BARRERAS BIOLÓGICAS ACTIVAS — ZONAS ALPHA, BETA, GAMMA, DELTA" } },
    { speaker:"ANALISTA — Ing. Tomas Reyes", speakerClass:"char-analista",
      text:"Funciona. Por ahora. CG-001 sigue activo dentro de los perimetros pero no se propaga fuera." },
    { speaker:"MENTORA — Dra. Elena Vargas", speakerClass:"char-mentora",
      text:"Ahora tenemos tiempo para estudiarlo. Para entender el Gen D. Para saber que hace realmente.",
      choices:[
        { label:"Cuanto tiempo tenemos antes de que mute y rompa la contencion?", next:"END_B2", safe:true },
        { label:"Deberíamos publicar los datos abiertamente para que todo el mundo investigue.", next:"END_B2", safe:false,
          penalty:{ reason:"Propusiste publicar datos de un agente en contencion activa sin protocolo de seguridad.",
            lesson:"Los datos de agentes biologicos en contencion activa siguen protocolos estrictos de bioseguridad. Publicar informacion de secuenciacion de un agente no neutralizado podria facilitar su recreacion accidental. La ciencia abierta tiene limites cuando hay riesgo biologico activo." } },
        { label:"Necesitamos descifrar el Gen D antes de cualquier otra decision.", next:"END_B2", safe:true },
      ] },
  ], next:"END_B2" },

  END_B2:{ type:"sequence", steps:[
    { speaker:"SISTEMA IA", speakerClass:"char-sistema",
      text:"Proyeccion: con las barreras actuales, probabilidad de contencion estable:\n\n  6 meses: 73%\n  18 meses: 41%\n  3 anos: 12%",
      alert:{ type:"warn", msg:"◆ PROYECCIÓN — CONTENCION ESTABLE DECRECIENTE — INVESTIGACIÓN ACTIVA REQUERIDA" } },
    { speaker:"MENTORA — Dra. Elena Vargas", speakerClass:"char-mentora",
      text:"El tiempo juega en nuestra contra. Pero tambien es el unico recurso que tenemos para entender que es esto realmente antes de decidir si destruirlo.\n\n(mira el mapa)\n\nPor ahora... funciona." },
    { speaker:null, speakerClass:"char-narrator",
      text:"CUATRO MESES DESPUÉS\n\nLas zonas de contencion siguen activas. El Gen D ha sido parcialmente descifrado.\n\nLos investigadores encontraron algo que nadie esperaba." },
  ], next:"ENDING_B" },

  ENDING_B:{ type:"ending",
    title:"FINAL B — CONTENCIÓN",
    subtitle:"EL EQUILIBRIO FRÁGIL",
    quote:"Decidiste que no todo lo que existe necesita ser destruido.\nQue la contencion, a veces, es la forma mas honesta de decir:\naun no entendemos esto lo suficiente.\n\nLas barreras se sostienen.\nLos investigadores trabajan.\nEl Gen D empieza a revelar su logica.\n\nY lo que encuentran cambia todo lo que creian saber\nsobre como la vida se organiza a si misma.",
    ending_text:"El informe del cuarto mes incluye un hallazgo sin precedente:\n\nEl patron repetido del Gen D no codifica ninguna proteina conocida.\nCodifica una senal. Una frecuencia biologica que CG-001 emite de forma continua.\n\nHacia ningun receptor conocido.\n\nO hacia uno que todavia no hemos encontrado.\n\nLas zonas de contencion siguen activas.\nLa investigacion, tambien.",
  },

  END_C:{ type:"sequence", steps:[
    { speaker:null, speakerClass:"char-narrator",
      text:"SALA DE SÍNTESIS GENÓMICA — 3 HORAS DESPUÉS\n\nTu y la Dra. Vargas frente a una pantalla en blanco.\n\nTodo el mundo les dijo que no.",
      alert:{ type:"warn", msg:"◆ PROTOCOLO NO AUTORIZADO — TRANSMISIÓN GENÓMICA EXPERIMENTAL — RIESGO NIVEL MÁXIMO" } },
    { speaker:"MENTORA — Dra. Elena Vargas", speakerClass:"char-mentora",
      text:"El Director lo va a cancelar en cuanto se entere.\n\nEstas seguro?" },
    { speaker:"TU", speakerClass:"char-player",
      text:"CG-001 no tiene genes de patogenicidad. No tiene toxinas. No tiene sistemas de ataque activo.\n\nEmite una senal que no podemos descifrar.\n\nY si no esta atacando? Y si esta... buscando algo?" },
    { speaker:"MENTORA — Dra. Elena Vargas", speakerClass:"char-mentora",
      text:"(silencio largo)\n\nQue le mandamos?" },
    { speaker:"TU", speakerClass:"char-player",
      text:"Lo unico que tenemos en comun con cualquier forma de vida.\n\nEl codigo genetico universal.\n\nLe mandamos el codon de inicio, los veinte aminoacidos estandar y los tres codones de stop.\nLa gramatica basica de la biologia.",
      choices:[
        { label:"(Iniciar la transmision.)", next:"END_C2", safe:true },
        { label:"(Enviar primero solo el codon AUG — un saludo minimo.)", next:"END_C2", safe:true },
        { label:"(Transmitir tambien el genoma humano completo para establecer contexto.)", next:"END_C2", safe:false,
          penalty:{ reason:"Transmitir el genoma humano completo a un agente desconocido sin protocolo de seguridad.",
            lesson:"En comunicacion biologica experimental, el principio de minima informacion es clave. Transmitir el genoma humano daria informacion sobre nuestro sistema inmune y mecanismos de replicacion. Siempre se comienza con secuencias universales neutras, no con datos sensibles." } },
      ] },
  ], next:"END_C2" },

  END_C2:{ type:"sequence", steps:[
    { speaker:null, speakerClass:"char-narrator",
      text:"La transmision dura 4 segundos.\n\nLuego silencio.\n\nDos minutos. Cinco. Diez.",
      alert:{ type:"info", msg:"◆ TRANSMISIÓN ENVIADA — ESPERANDO RESPUESTA — T+00:10:00" } },
    { speaker:"ANALISTA — Ing. Tomas Reyes", speakerClass:"char-analista",
      text:"(desde la puerta, en voz baja)\n\nEl Director sabe. Viene para aca." },
    { speaker:"SISTEMA IA", speakerClass:"char-sistema",
      text:"ANOMALIA DETECTADA.\n\nLos patrones de propagacion de CG-001 estan cambiando.\n\nNo se esta expandiendo.\n\nSe esta... retrayendo.",
      alert:{ type:"success", msg:"✓ CAMBIO DE PATRÓN — PROPAGACIÓN DETENIDA — SEÑAL DE RESPUESTA DETECTADA — ANALIZANDO..." } },
    { speaker:"MENTORA — Dra. Elena Vargas", speakerClass:"char-mentora",
      text:"(en voz baja, casi para si misma)\n\nRespondio." },
    { speaker:null, speakerClass:"char-narrator",
      text:"La secuencia de respuesta tarda 40 segundos en decodificarse.\n\nContiene el codigo genetico universal completo.\n\nMas algo adicional.\n\nAlgo que no existe en ninguna base de datos." },
  ], next:"ENDING_C" },

  ENDING_C:{ type:"ending",
    title:"FINAL C — COMUNICACIÓN",
    subtitle:"EL DIÁLOGO QUE CAMBIÓ TODO",
    quote:"La humanidad siempre penso que dominaba la biologia.\nNunca entendimos que solo la estabamos empezando a leer.\n\nEnviamos un mensaje en el unico idioma verdaderamente universal:\nel codigo genetico.\n\nY algo que nunca habiamos visto\nrespondio en el mismo idioma.\n\nCon algo que nunca habiamos dicho.",
    ending_text:"Los virologos, los filologos, los linguistas y los bioinformaticos pasaron tres anos\ndescifrando los 47 codones adicionales de la respuesta.\n\nNo codifican ninguna proteina.\nNo codifican ninguna senal metabolica.\n\nCodifican una instruccion.\n\nUna instruccion que, cuando se lee en el contexto del genoma completo de CG-001,\ndesencadena un proceso que ningun modelo evolutivo habia predicho.\n\nLos ecologos lo llaman 'la transicion'.\nLos biologos lo llaman 'el siguiente paso'.\n\nNadie sabe todavia a donde lleva.",
  },

  POST_CREDITS:{ type:"post_credits" },
};

window.SCENE_LABELS = {
  INTRO:"Acto I — El Llamado",
  SCENE2:"Acto I · Llegada",
  SCENE2B:"Acto I · Briefing",
  SCENE3:"Acto I · Primer Caso",
  MG1:"Laboratorio · Alineamiento BLAST",
  SCENE4:"Acto II — El Descubrimiento",
  SCENE5:"Acto II · Analisis mRNA",
  MG2:"Laboratorio · Traduccion de Codones",
  SCENE6:"Acto II · Mutacion Nonsense",
  SCENE7:"Acto III — La Crisis",
  SCENE7B:"Acto III · Preparacion Filogenetica",
  MG3:"Laboratorio · Arbol Filogenetico",
  SCENE8:"Acto III · Transferencia Horizontal",
  SCENE8B:"Acto III · Analisis Final",
  MG4:"Laboratorio · Clasificacion de Mutaciones",
  SCENE9:"Acto IV — El Climax",
  SCENE10:"Acto IV · La Pregunta",
  DECISION:"Decision Final",
  END_A:"Final A · Neutralizacion",
  ENDING_A:"Creditos A",
  END_B:"Final B · Contencion",
  END_B2:"Final B · Proyeccion",
  ENDING_B:"Creditos B",
  END_C:"Final C · Comunicacion",
  END_C2:"Final C · La Respuesta",
  ENDING_C:"Creditos C",
};
